/// Static, human-readable documentation of the public backend API.
///
/// The document is a compile-time constant: it reads no actor state and takes
/// no parameters, so it is safe to call at any time, including before the
/// caller has registered with the authorization system.
///
/// The text is assembled from single-line literals joined with newlines
/// because this toolchain's `moc` does not support triple-quoted multiline
/// string literals.
mixin () {
  public query func getApiDoc() : async Text {
    let lines : [Text] = [
      "# Kredit Uang — Backend API",
      "",
      "Backend canister untuk aplikasi pratinjau pembayaran **Kredit Uang**. Aplikasi ini",
      "bersifat **UI / non-transaksional**: tidak ada uang sungguhan yang diproses, tidak",
      "ada koneksi ke bank, payment gateway, atau rekening mana pun. Backend hanya",
      "menyimpan satu tagihan aktif dan menandainya sebagai lunas ketika pengguna",
      "menekan tombol pembayaran di antarmuka.",
      "",
      "## Metode publik",
      "",
      "### `getActiveBill : () -> (BillView) query`",
      "",
      "Mengembalikan tagihan aktif yang ditampilkan pada layar utama.",
      "",
      "- **Autentikasi:** tidak diperlukan. Dapat dipanggil oleh siapa saja, termasuk",
      "  pemanggil anonim.",
      "- **Otorisasi:** tidak ada pemeriksaan peran.",
      "- **Sifat:** `query` — hanya baca, cepat, dan tidak mereplikasi perubahan.",
      "- **Nilai awal:** `id = 1`, `title = \"TAGIHAN SAAT INI\"`,",
      "  `amount = 1_200_000`, `confirmationStatus = \"TERKONFIRMASI\"`,",
      "  `paymentStatus = \"Belum Lunas\"`, `paid = false`, `updatedAt = 0`.",
      "",
      "### `payActiveBill : () -> (BillView)`",
      "",
      "Menandai tagihan aktif sebagai sudah dibayar dan mengembalikan status terbarunya.",
      "",
      "- **Autentikasi:** tidak diperlukan. Dapat dipanggil oleh siapa saja, termasuk",
      "  pemanggil anonim.",
      "- **Otorisasi:** tidak ada pemeriksaan peran.",
      "- **Sifat:** update — perubahan dipersistenkan.",
      "- **Efek:** mengubah `paymentStatus` menjadi `\"Lunas\"`, `paid` menjadi `true`,",
      "  dan `updatedAt` menjadi waktu saat ini dalam nanodetik. `id`, `title`,",
      "  `amount`, dan `confirmationStatus` tidak berubah.",
      "- **Idempoten:** memanggil ulang pada tagihan yang sudah lunas tidak menghasilkan",
      "  kesalahan dan tidak menggandakan apa pun. Setiap panggilan tetap mengembalikan",
      "  keadaan lunas yang sama; hanya `updatedAt` yang diperbarui ke waktu panggilan",
      "  terakhir. Aman untuk dicoba ulang setelah kegagalan jaringan.",
      "- **Tidak destruktif:** tidak ada penghapusan data dan tidak ada efek samping",
      "  lain di luar penandaan lunas.",
      "",
      "### `getCallerUserRole : () -> (UserRole) query`",
      "",
      "Mengembalikan peran pemanggil: `#admin`, `#user`, atau `#guest`.",
      "",
      "- **Autentikasi:** pemanggil anonim menerima `#guest` tanpa kesalahan.",
      "- **Otorisasi:** tidak ada pemeriksaan peran.",
      "- **Error:** pemanggil yang sudah masuk (non-anonim) tetapi belum terdaftar",
      "  menyebabkan trap dengan pesan `User is not registered`.",
      "",
      "### `isCallerAdmin : () -> (Bool) query`",
      "",
      "Mengembalikan `true` jika pemanggil memiliki peran `#admin`.",
      "",
      "- **Autentikasi:** pemanggil anonim menerima `false`.",
      "- **Otorisasi:** tidak ada pemeriksaan peran.",
      "- **Error:** pemanggil yang sudah masuk tetapi belum terdaftar menyebabkan trap",
      "  dengan pesan `User is not registered`.",
      "",
      "### `assignCallerUserRole : (Principal, UserRole) -> ()`",
      "",
      "Menetapkan peran kepada sebuah principal.",
      "",
      "- **Autentikasi:** pemanggil harus sudah masuk (non-anonim) dan terdaftar.",
      "- **Otorisasi:** hanya `#admin`. Pemanggil lain menyebabkan trap dengan pesan",
      "  `Unauthorized: Only admins can assign user roles`.",
      "- **Sifat:** update — perubahan dipersistenkan.",
      "",
      "### `_initialize_access_control : () -> ()`",
      "",
      "Mendaftarkan pemanggil ke sistem otorisasi.",
      "",
      "- **Autentikasi:** pemanggil harus sudah masuk (non-anonim). Pemanggil anonim",
      "  diabaikan tanpa efek dan tanpa kesalahan.",
      "- **Perilaku:** pemanggil pertama yang mendaftar menerima peran `#admin`;",
      "  pemanggil berikutnya menerima `#user`. Pemanggil yang sudah terdaftar tidak",
      "  berubah perannya.",
      "- **Catatan:** pendaftaran hanya terjadi ketika pengguna masuk melalui frontend",
      "  aplikasi. Principal yang belum pernah melakukannya tetap belum terdaftar,",
      "  meskipun principal tersebut milik pemilik aplikasi.",
      "",
      "### `_internet_identity_sign_in_start : () -> (Blob)` dan `_internet_identity_sign_in_finish : () -> (Result<(), Error>)`",
      "",
      "Alur masuk Internet Identity yang dipakai frontend. `start` menerbitkan",
      "tantangan; `finish` memverifikasi atribut identitas dan mendaftarkan pemanggil",
      "melalui jalur yang sama dengan `_initialize_access_control`.",
      "",
      "## Identitas dan derivasi principal",
      "",
      "Frontend aplikasi ini menyematkan *derivation origin* Internet Identity, yang",
      "dipublikasikan pada `/.well-known/ii-derivation-origin` bila tersedia. Agen yang",
      "sudah memegang otorisasi Internet Identity pengguna menurunkan principal per",
      "aplikasi yang benar terhadap origin tersebut, misalnya:",
      "",
      "    icp identity link web <name> --app <host>",
      "",
      "Delegasi semacam itu bertindak dengan wewenang penuh pengguna di aplikasi ini",
      "sampai masa berlakunya habis. Principal yang diturunkan terhadap origin berbeda",
      "adalah principal yang berbeda pula, sehingga tidak akan dikenali sebagai",
      "pengguna yang sudah terdaftar.",
      "",
      "## Prasyarat pendaftaran",
      "",
      "Pemanggil API langsung yang ingin memakai endpoint berperan harus mendaftar",
      "terlebih dahulu dengan memanggil `_initialize_access_control` satu kali sebagai",
      "pemanggil yang sudah masuk. Pemanggil pertama menerima `#admin`, pemanggil",
      "berikutnya menerima `#user`. Pemanggil anonim atau yang belum terdaftar akan",
      "menerima trap `User is not registered` pada endpoint yang memeriksa peran",
      "(termasuk `getCallerUserRole` dan `isCallerAdmin`), atau trap",
      "`Unauthorized: Only admins can assign user roles` pada `assignCallerUserRole`.",
      "",
      "## Satuan dan pengkodean",
      "",
      "- `amount` adalah `Nat` dalam **rupiah bulat** (tanpa sen, tanpa pecahan).",
      "  Nilai tagihan aktif adalah `1_200_000`.",
      "- `updatedAt` adalah `Nat` dalam **nanodetik** sejak Unix epoch. Nilai `0`",
      "  berarti tagihan belum pernah diperbarui.",
      "- `id` adalah `Nat`; tagihan aktif memiliki `id = 1`.",
      "- `paid` adalah `Bool`; `paymentStatus` adalah teks tampilan berbahasa Indonesia",
      "  (`\"Belum Lunas\"` atau `\"Lunas\"`).",
      "- `confirmationStatus` adalah teks tampilan (`\"TERKONFIRMASI\"`).",
      "- `UserRole` adalah varian Candid: `#admin`, `#user`, `#guest`.",
      "",
      "## Siklus hidup dan polling",
      "",
      "Tagihan aktif selalu ada — backend tidak pernah mengembalikan nilai kosong atau",
      "`null` dari `getActiveBill`. Siklus hidupnya hanya dua keadaan:",
      "",
      "1. **Belum lunas** — `paid = false`, `paymentStatus = \"Belum Lunas\"`.",
      "2. **Lunas** — `paid = true`, `paymentStatus = \"Lunas\"`.",
      "",
      "Transisi hanya terjadi lewat `payActiveBill` dan bersifat satu arah; tidak ada",
      "endpoint untuk mengembalikan tagihan ke keadaan belum lunas. Karena itu polling",
      "`getActiveBill` cukup dilakukan sekali saat memuat layar, dan setelah",
      "`payActiveBill` selesai tidak ada perubahan lebih lanjut yang perlu ditunggu.",
      "Tidak ada proses latar belakang, antrean, atau pekerjaan asinkron yang perlu",
      "dipantau.",
      "",
      "## Kesalahan dan batasan",
      "",
      "- Endpoint tagihan (`getActiveBill`, `payActiveBill`) tidak pernah melakukan",
      "  trap dan tidak memiliki kasus kesalahan yang dapat diperbaiki pemanggil.",
      "- Endpoint otorisasi dapat melakukan trap seperti dijelaskan di atas; trap",
      "  sampai ke frontend sebagai penolakan buram tanpa muatan terstruktur.",
      "- Tidak ada batas laju, kuota, atau batas ukuran masukan yang diberlakukan",
      "  backend, karena tidak ada endpoint yang menerima masukan pengguna selain",
      "  `assignCallerUserRole`.",
      "",
      "## Catatan penting",
      "",
      "- Nama field pada record tagihan adalah **`title`**, bukan `label`. `label`",
      "  adalah kata kunci yang dipesan di Motoko sehingga tidak dapat dipakai sebagai",
      "  nama field.",
      "- Aplikasi ini adalah **pratinjau UI non-transaksional**. Tidak ada pembayaran",
      "  nyata yang diproses, dan tidak ada data rekening, kartu, PIN, atau OTP yang",
      "  diminta maupun disimpan.",
      "- Backend tidak mengekspos entitas OQL apa pun; tagihan aktif adalah satu record",
      "  tunggal, bukan koleksi.",
    ];
    lines.values().join("\n");
  };
};
